version: "3.4"
services:

  dev: &dev
    build:
      dockerfile: "./docker/Dockerfile"
      context: "."
    image: "extra-model-dev"
    volumes:
      - ./extra_model:/package/extra_model
      - ./tests:/package/tests
      - ./docs:/package/docs
      - ./site:/package/site
      - ./mkdocs.yml:/package/mkdocs.yml
      - ./embeddings:/package/embeddings
      - ./io:/io

  # download embeddings
  setup:
    <<: *dev
    entrypoint: "extra-model-setup"

  # run extra-model
  extra-model:
    <<: *dev
    entrypoint: "extra-model"

  # run test & lint suite
  test:
    <<: *dev
    command: docker/run_tests.sh --format-code

  # generate and serve the project documentation locally
  mkdocs: &mkdocs
    <<: *dev
    entrypoint: "mkdocs"
    ports:
      - "8000:8000"
    command: ["serve", "--dev-addr=0.0.0.0:8000"]
