name: "Install spacy language pack"
description: "Install spacy language pack"
inputs:
  pack:
    description: "Name of the language module to be installed"
    default: "en_core_web_sm"
    required: false
runs:
  using: "composite"
  steps:
    - name: "Install spacy language pack"
      run: "$GITHUB_ACTION_PATH/action.sh"
      shell: "bash"
      env:
        SPACY_LANGUAGE_PACKAGE: ${{ inputs.pack }}
